version: 2
updates:
  - package-ecosystem: "pip" # Para requirements.txt
    directory: "."
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions" # Seguridad en workflows
    directory: "."
    schedule:
      interval: "weekly"